Update Navbar
amri-tah/LeetPath pull request #6
Opened 2024-12-22 14:15 UTC by MithileshwaranS

issue #1  is done and hamburger menu is implemented and proper spacing and alignments are implemented

2024-12-23 13:46 UTC, MithileshwaranS commented
@amri-tah  please review the changes

2024-12-23 16:55 UTC, VishalTheHuman commented
@MithileshwaranS can you deploy it in vercel in your repo

2024-12-24 13:21 UTC, amri-tah requested changes
Overall good work, just a few suggestions/issues:
- The navbar is overflowing in desktop view when hovered on. Its perfect in mobile view.
- Features section on desktop view was better before these changes were made
- The mobile view of home page is also good, just needs a bit more spacing between each section

Hope youre also working on making the other pages responsive!

2024-12-25 14:51 UTC, MithileshwaranS commented
> Overall good work, just a few suggestions/issues:
> 
> * The navbar is overflowing in desktop view when hovered on. Its perfect in mobile view.
> * Features section on desktop view was better before these changes were made
> * The mobile view of home page is also good, just needs a bit more spacing between each section
> 
> Hope youre also working on making the other pages responsive!

Hey @amri-tah can i get more info on feature section

2024-12-25 14:53 UTC, MithileshwaranS commented
> @MithileshwaranS can you deploy it in vercel in your repo

when i try to deploy it in vercel. The spacing and alignments are not reflecting in the vercel page.i need some help finding out what is the issue

2024-12-26 18:07 UTC, MithileshwaranS commented
@amri-tah 
The changes are done as per mentioned.Let me know if there are any other changes to b done

2024-12-31 11:57 UTC, amri-tah requested changes
Looks good! The navbar overflow on hover in desktop view is still not resolved though

2025-01-01 15:07 UTC, amri-tah requested changes
Doesn't look like the hamburger menu is working anymore? 🥲 Please take a look, otherwise everything looks good to me!

Also, will you be working on making the rest of the pages responsive as well, or shall I close this PR ?

2025-01-01 16:13 UTC, MithileshwaranS commented
> Doesn't look like the hamburger menu is working anymore? 🥲 Please take a look, otherwise everything looks good to me!
> 
> Also, will you be working on making the rest of the pages responsive as well, or shall I close this PR ?

Hey sorry for the issue.Resolved the hamburger issue now and it works now.Also i have made changes to rest of the pages please do check and let me know any changes required

2025-01-01 17:03 UTC, amri-tah commented
The home page and navbar is good to go, but the other pages don't seem responsive yet:

![image](https://github.com/user-attachments/assets/0e75f689-5252-43b2-9595-673b566f750f)
![image](https://github.com/user-attachments/assets/ec66ef93-5ac0-472f-b618-025902405df3)

Do let us know if you want to continue working on it or want to close this PR!

2025-01-02 14:55 UTC, MithileshwaranS commented
> @MithileshwaranS can you deploy it in vercel in your repo

@VishalTheHuman here is the link for that 
https://leet-path.vercel.app/

2025-01-02 14:57 UTC, MithileshwaranS commented
> The home page and navbar is good to go, but the other pages don't seem responsive yet:
> 
> ![image](https://private-user-images.githubusercontent.com/111682039/399577016-0e75f689-5252-43b2-9595-673b566f750f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzAxMTUsIm5iZiI6MTczNTgyOTgxNSwicGF0aCI6Ii8xMTE2ODIwMzkvMzk5NTc3MDE2LTBlNzVmNjg5LTUyNTItNDNiMi05NTk1LTY3M2I1NjZmNzUwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDU2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWYxODk3ODc4NGU2MTIwYzA2YjI2YTJlMDMyNjdhM2EzM2I5YjdmZDhmOGI2OWViMGU4ODVhNjE1MjNjNTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MRgKzj9WB2rpaGUmJxEARNQMspaghC16xmMVW3LYSLs) ![image](https://private-user-images.githubusercontent.com/111682039/399577093-ec66ef93-5ac0-472f-b618-025902405df3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzAxMTUsIm5iZiI6MTczNTgyOTgxNSwicGF0aCI6Ii8xMTE2ODIwMzkvMzk5NTc3MDkzLWVjNjZlZjkzLTVhYzAtNDcyZi1iNjE4LTAyNTkwMjQwNWRmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQxNDU2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGMwYTRhNzJkYjA3NTNlZWJkMWYyMWU0OWU3YWZiZWVkZmE1NDBhYTZmYTRkY2ZmYzcyNzJjMjBiODMwN2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q7n7sObE28hG-aJs9preYvzilhUy1EuTpaJaaK9YEmU)
> 
> Do let us know if you want to continue working on it or want to close this PR!

@amri-tah i would like to continue working 
I have made changes for the remaining pages,Review it and let me know if there are any changes

2025-01-03 08:52 UTC, amri-tah commented
Looks great! Please resolve conflicts so that I can merge it @MithileshwaranS

2025-01-03 10:53 UTC, MithileshwaranS commented
@amri-tah Resolved the conflicts

2025-01-07 16:39 UTC, amri-tah commented
LGTM! Your bounty will be assigned soon, thank you for your contribution 🫡

2025-01-07 16:39 UTC, amri-tah approved these changes

2025-01-07 16:40 UTC, amri-tah approved these changes

2025-01-07 16:41 UTC, merged

2025-01-07 16:54 UTC, amri-tah commented
/bounty 70 @MithileshwaranS